#comando para dar el nombre del flujo:
name: CI pipeline

#indica cuando se ejecuta el flujo:
on:
  pull_request:
  push:
    branches:
      - develop

#acciones que se ejecutaran en el servidor:
jobs:
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository (git clone)
        uses: actions/checkout@v4

      - name: Setup node (instalar node)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas del frontend
        run: npm run test

  build-frontend:
    runs-on: ubuntu-latest
    needs: test-frontend
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository (git clone)
        uses: actions/checkout@v4

      - name: Setup node (instalar node)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Construir frontend
        run: npm run build

  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Ejecutar pruebas del servidor (Maven)
        run: chmod +x mvnw && ./mvnw test

  build-backend:
    runs-on: ubuntu-latest
    needs: test-backend
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Compilar y empaquetar el servidor (Maven)
        run: chmod +x mvnw && ./mvnw clean package -DskipTests

      - name: Subir artefacto del Build (Backend)
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/target/*.jar
